### ISSUE TITLE
Intraday data, classification, DL

### ISSUE THREAD

**Issue by MislavSag** [tylerJPike/OOS#7]
Hi,

I have just skimed your package. Even there are some packages for ts, like modeltime and mlr3 forecasts I look forward to try your package. I have few questions after first look:
1. Is there any reason intraday frequency is not available in freq argument? I am using intraday trading data very often so I am very interesed in this feature.
2. Is it possible to apply classification tasks with RF or NN models? Do you plan to add this support in the future?
3. Do you plan to add deepearning models in the future using keras or pytorch?

**Comment by tylerJPike** [comment]
Hello, 

Thanks for looking through the package. The key difference between OOS and the other ts forecasting packages is that it operates out-of-sample by construction. That is, it re-cleans data and re-trains models each forecast.date and is careful not to introduce look-ahead bias into its information set via data cleaning or forecasts via model training. Other packages tend to fit the model once, leaving the user to construct the out-of-sample data cleaning and forecast exercise on their own. 

As for the extensions you suggest, I think they are all good ideas, and most are already in my plans for future versions of the package. More specifically, the current development plan is:

   version 1.1: add hierarchical forecasting, add classification, add upgraded tree algorithms (such as local linear forests and XGboost
   version 1.2: add genetic algorithms for forecast combinations, add deep learning via Keras (potentially pytorch), add PLS for dimension reduction

However, as you might note, this plan does not include incorporating intraday frequencies, and I think that has been a mistake on my part. Based on your comments, I think I will prioritize intraday functionality and try to include it in version 1.1.
